add wave pong_tb/clk100
add wave pong_tb/clk25
add wave pong_tb/rst 
add wave pong_tb/en 
add wave pong_tb/red
add wave pong_tb/green
add wave pong_tb/blue
add wave pong_tb/hPulse 
add wave pong_tb/pong_inst/vga_inst/HSync
add wave pong_tb/pong_inst/vga_inst/vga_counter_inst/hsync_counter_inst/countOut
add wave pong_tb/vPulse
add wave pong_tb/pong_inst/vga_inst/VSync
add wave pong_tb/pong_inst/vga_inst/vga_counter_inst/vsync_counter_inst/countOut
add wave pong_tb/pong_inst/vga_inst/vga_counter_inst/hsync_counter_inst/doneOut