add wave pong_tb/clk
add wave pong_tb/vga_clk
add wave pong_tb/rst 
add wave pong_tb/en 
add wave pong_tb/hPulse 
add wave pong_tb/vPulse
add wave pong_tb/red
add wave pong_tb/green
add wave pong_tb/blue
add wave pong_tb/pong_inst/vga_inst/vga_counter_inst/hsync_counter_inst/countOut
add wave pong_tb/pong_inst/vga_inst/vga_counter_inst/vsync_counter_inst/countOut